[env:receiver]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  AccelStepper
  RobTillaart/AS5600
src_filter = +<receiver/*>

[env:sender]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
src_filter = +<sender/*>
