[platformio]
default_envs = controller, head
src_dir = .

[env:controller]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages = framework-arduinoespressif32@^3
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
build_flags = -std=gnu++17 -Icommon
build_unflags = -std=gnu++11
src_filter = +<controller/src/*> +<common/*>

[env:head]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages = framework-arduinoespressif32@^3
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  AccelStepper
  RobTillaart/AS5600
build_flags = -std=gnu++17 -Icommon
build_unflags = -std=gnu++11
src_filter = +<head/src/*> +<common/*>
